### ISSUE TITLE
Improve layout of criteria & actions

### ISSUE THREAD

**Issue by klequis** [klequis/private-money-client#11]
1. Improve horizontal and vertical spacing
2. Resize Select & edit boxes
     - Selects should be wide enough to fit the largest selection word.
     - The edit box needs to be considerably wider as descriptions can be very long.
3. Check boxes should align with the vertical center of the criteria row
4. Headings are crammed together
5. Entire Create Rule should have some margin. Probably just wrap the entire thing in Container Fluid.

Dependencies

- [ ] #19 Actions edit boxes should have labels

**Comment by dhaef** [comment]
@klequis could you add steps to set up locally so I could work on this?

**Comment by klequis** [comment]
@dhaef I'm working on some data for you to use. Have been using my personal banking data so far. Should a starter set done sometime tomorrow.

I created issue #16 to discuss setup.

**Comment by klequis** [comment]
@dhaef database and server setup instructions are now in #16

**Comment by klequis** [comment]
Nicely done. Thank you!
