### ISSUE TITLE
Style txTbl heading row

### ISSUE THREAD

**Issue by klequis** [klequis/private-money-client#23]
- [ ] Column names larger so not dwarfed by edit boxes
- [ ] Column names proper case and not short names (use the txFields .description property)
- [ ] Left align date, acctId & description
- [ ] Right align amount, category1, category2, type, omit

**Comment by dhaef** [comment]
When I change the fieldName in TxTblHead from .name to .description I get the following error and I'm unsure why

<img width="1280" alt="Screen Shot 2020-12-24 at 6 06 58 PM" src="https://user-images.githubusercontent.com/40745303/103108169-37d59800-4613-11eb-8ff6-4d00bbeb903f.png">

**Comment by klequis** [comment]
TxTblHead is passing fieldName to TxColHead where fieldName is used in
```
_dispatch(updateFilters({ name: fieldName, value: value }))
```
as well as
```
const filterValue = useSelector(state => selectTxTblFilterValue(fieldName,
state))
```
and `SortIcons` also needs field.name, not field.description.

I think if you pass a second prop from TxTblHead to TxColHead of
fieldDescription, you can replace `fieldName` with `fieldDescription` in
both instances of `<FieldNameDiv>`, which I think are the only places
field.description is needed.  I guess if you want to be precise, you could
also rename `FieldNameDiv` to `FieldDescriptionDiv`.

**Comment by klequis** [comment]
Regarding the screen shot you posted, I'll note that the error at the top
is a sub directory of /node_modules/. You need to go down to the first
error in the list that isn't under /node_modules and that will be the line
of Private Money code that produced the error.

**Comment by klequis** [comment]
Completed
