### ISSUE TITLE
Style Transactions Table options

### ISSUE THREAD

**Issue by klequis** [klequis/private-money-client#24]
![image](https://user-images.githubusercontent.com/18337376/102948049-cadaca80-4479-11eb-8b24-accb5b536298.png)

- [ ] Add horizontal spacing to 'Show omitted'
- [ ] Make row labels (Transactions & Category) bold
- [ ] Remove debug background colors

**Comment by p-a-d-y** [comment]
When i run it on my machine it has blank output..is there any special thing require to run it.

**Comment by klequis** [comment]
Hi p-a-d-y,

The setup directions are in [the wiki](
https://github.com/klequis/private-money-client/wiki). They are numbered 1
- 6. If you have any questions/issues let me know.

**Comment by klequis** [comment]
done

**Comment by klequis** [comment]
done
